//* 포장지, 리본, 꽃 종류 컨텐츠
//* 색깔 종류
const white = "white",
  ivory = "ivory",
  pink = "pink",
  blue = "blue",
  brown = "brown",
  gray = "gray",
  lightpink = "lightpink",
  purple = "purple",
  red = "red",
  yellow = "yellow";

//* 포장지
export const wrapper = [
  {
    id: 1,
    title: "종이 포장지",
    contents: "어디에나 잘 어울리는 \n 크래프트 소재 종이 포장지",
    color: brown,
  },
  {
    id: 2,
    title: "흰색 포장지",
    contents: "차분하고 깔끔한 느낌의 \n 흰색 포장지",
    color: white,
  },
  {
    id: 3,
    title: "미색 포장지",
    contents: "부드러운 느낌을 주는\n 미색(아이보리색) 포장지",
    color: ivory,
  },
  {
    id: 4,
    title: "분홍색 포장지",
    contents: "따뜻하고 사랑스러운 느낌의 \n 분홍색 포장지",
    color: pink,
  },
  {
    id: 5,
    title: "파란색 포장지",
    contents: "누구에게나 선물하기 좋은 \n 파란색 포장지",
    color: blue,
  },
  {
    id: 6,
    title: "회색 포장지",
    contents: "꽃을 더 돋보이게 해주는 \n 회색 포장지",
    color: gray,
  },
];

//* 리본
export const ribbon = [
  {
    id: 1,
    title: "끈 리본",
    contents: "종이 포장지와 잘 어울리는 \n 끈 리본",
    color: brown,
  },
  {
    id: 2,
    title: "흰색 리본",
    contents: "깔끔하고 밝은 흰색 리본",
    color: white,
  },
  {
    id: 3,
    title: "미색 리본",
    contents: "부드러운 느낌의 미색 리본",
    color: ivory,
  },
  {
    id: 4,
    title: "분홍색 리본",
    contents: "귀여운 느낌의 분홍색 리본",
    color: pink,
  },
  {
    id: 5,
    title: "파란색 리본",
    contents: "밝은 느낌의 옅은 파란색 리본",
    color: blue,
  },
  {
    id: 6,
    title: "회색 리본",
    contents: "꽃을 더 돋보이게 해주는 \n 회색 리본",
    color: gray,
  },
];

//* 꽃
export const flower = [
  {
    id: 1,
    name: "calla",
    contents: "카라입니다.",
    title: "흰색 카라",
    color: white,
  },
  {
    id: 2,
    name: "calla",
    contents: "카라입니다.",
    title: "옅은 분홍색 카라",
    color: lightpink,
  },
  {
    id: 3,
    name: "calla",
    contents: "카라입니다.",
    title: "분홍색 카라",
    color: pink,
  },
  {
    id: 4,
    name: "calla",
    contents: "카라입니다.",
    title: "노란색 카라",
    color: yellow,
  },
  {
    id: 5,
    name: "carnation",
    title: "흰색 카네이션",
    contents: "카네이션입니다.",
    color: white,
  },
  {
    id: 6,
    name: "carnation",
    title: "분홍색 카네이션",
    contents: "카네이션입니다.",
    color: pink,
  },
  {
    id: 7,
    name: "carnation",
    title: "빨간색 카네이션",
    contents: "카네이션입니다.",
    color: red,
  },
  {
    id: 8,
    name: "carnation",
    title: "노란색 카네이션",
    contents: "카네이션입니다.",
    color: yellow,
  },
  {
    id: 9,
    name: "hydrangea",
    title: "흰색 수국",
    contents: "수국입니다.",
    color: white,
  },
  {
    id: 10,
    name: "hydrangea",
    title: "분홍색 수국",
    contents: "수국입니다.",
    color: pink,
  },
  {
    id: 11,
    name: "hydrangea",
    title: "보라색 수국",
    contents: "수국입니다.",
    color: purple,
  },
  {
    id: 12,
    name: "hydrangea",
    title: "푸른색 수국",
    contents: "수국입니다.",
    color: blue,
  },
  {
    id: 13,
    name: "peony",
    contents: "작약입니다.",
    title: "흰색 작약",
    color: white,
  },
  {
    id: 14,
    name: "peony",
    contents: "작약입니다.",
    title: "분홍색 작약",
    color: pink,
  },
  {
    id: 15,
    name: "peony",
    contents: "작약입니다.",
    title: "빨간색 작약",
    color: red,
  },
  {
    id: 16,
    name: "rose",
    contents: "장미입니다.",
    title: "흰색 장미",
    color: white,
  },
  {
    id: 17,
    name: "rose",
    contents: "장미입니다.",
    title: "붉은색 장미",
    color: red,
  },
  {
    id: 18,
    name: "rose",
    contents: "장미입니다.",
    title: "분홍색 장미",
    color: pink,
  },
  {
    id: 19,
    name: "rose",
    contents: "장미입니다.",
    title: "노란색 장미",
    color: yellow,
  },
  {
    id: 20,
    name: "rose",
    contents: "장미입니다.",
    title: "보라색 장미",
    color: purple,
  },
  {
    id: 21,
    name: "gypsophila",
    title: "노란색 안개꽃",
    contents: "안개꽃입니다.",
    color: yellow,
  },
  {
    id: 22,
    name: "gypsophila",
    title: "분홍색 안개꽃",
    contents: "안개꽃입니다.",
    color: pink,
  },
  {
    id: 23,
    name: "gypsophila",
    title: "빨간색 안개꽃",
    contents: "안개꽃입니다.",
    color: red,
  },
  {
    id: 24,
    name: "gypsophila",
    title: "보라색 안개꽃",
    contents: "안개꽃입니다.",
    color: purple,
  },
  {
    id: 25,
    name: "gypsophila",
    title: "푸른색 안개꽃",
    contents: "안개꽃입니다.",
    color: blue,
  },
  {
    id: 26,
    name: "gypsophila",
    title: "흰색 안개꽃",
    contents: "안개꽃입니다.",
    color: white,
  },
];
