//* 포장지, 리본, 꽃 종류 컨텐츠

//* 포장지
export const wrapper = [
  {
    id: 0,
    name: "종이 포장지",
    description: "어디에나 잘 어울리는 \n 크래프트 소재 종이 포장지",
    color: "brown",
    hex: "#dfd4b9",
  },
  {
    id: 1,
    name: "흰색 포장지",
    description: "차분하고 깔끔한 느낌의 \n 흰색 포장지",
    color: "white",
    hex: "#fffef4",
  },
  {
    id: 2,
    name: "미색 포장지",
    description: "부드러운 느낌을 주는 \n 미색(아이보리색) 포장지",
    color: "ivory",
    hex: "#ece6cc",
  },
  {
    id: 3,
    name: "분홍색 포장지",
    description: "따뜻하고 사랑스러운 느낌의 \n 분홍색 포장지",
    color: "pink",
    hex: "#f9eeee",
  },
  {
    id: 4,
    name: "파란색 포장지",
    description: "누구에게나 선물하기 좋은 \n 파란색 포장지",
    color: "blue",
    hex: "#e1e9f2",
  },
  {
    id: 5,
    name: "회색 포장지",
    description: "꽃을 더 돋보이게 해주는 \n 회색 포장지",
    color: "gray",
    hex: "#c0c0c0",
  },
];

//* 리본
export const ribbon = [
  {
    id: 0,
    name: "끈 리본",
    description: "종이 포장지와 잘 어울리는 \n 끈 리본",
    color: "brown",
  },
  {
    id: 1,
    name: "흰색 리본",
    description: "깔끔하고 밝은 흰색 리본",
    color: "white",
  },
  {
    id: 2,
    name: "미색 리본",
    description: "부드러운 느낌의 미색 리본",
    color: "ivory",
  },
  {
    id: 3,
    name: "분홍색 리본",
    description: "귀여운 느낌의 분홍색 리본",
    color: "pink",
  },
  {
    id: 4,
    name: "파란색 리본",
    description: "밝은 느낌의 옅은 파란색 리본",
    color: "blue",
  },
  {
    id: 5,
    name: "회색 리본",
    description: "꽃을 더 돋보이게 해주는 \n 회색 리본",
    color: "gray",
  },
];

//* 꽃
export const flower = [
  {
    id: 1,
    name: "calla",
    title: "흰색 카라",
    description: "순결함과 우아함의 상징으로, 부케로 많이 쓰이는 카라꽃입니다.",
    language: "순수, 천년의 사랑, 환희, 열정",
    color: "white",
  },
  {
    id: 2,
    name: "calla",
    title: "옅은 분홍색 카라",
    description: "순결함과 우아함의 상징으로, 부케로 많이 쓰이는 카라꽃입니다.",
    language: "순수, 천년의 사랑, 환희, 열정",
    color: "lightpink",
  },
  {
    id: 3,
    name: "calla",
    title: "분홍색 카라",
    description: "순결함과 우아함의 상징으로, 부케로 많이 쓰이는 카라꽃입니다.",
    language: "순수, 천년의 사랑, 환희, 열정",
    color: "pink",
  },
  {
    id: 4,
    name: "calla",
    title: "노란색 카라",
    description: "순결함과 우아함의 상징으로, 부케로 많이 쓰이는 카라꽃입니다.",
    language: "순수, 천년의 사랑, 환희, 열정",
    color: "yellow",
  },
  {
    id: 5,
    name: "carnation",
    title: "흰색 카네이션",
    description:
      "돌아가신 분을 대상으로 아직 남아있는 사랑을 전하는 데에 쓰이는 흰색 카네이션입니다.",
    language: "아직 당신을 사랑합니다.",
    color: "white",
  },
  {
    id: 6,
    name: "carnation",
    title: "분홍색 카네이션",
    description: "어버이나 스승께 선물하기 좋은 분홍색 카네이션입니다.",
    language: "감사와 아름다움",
    color: "pink",
  },
  {
    id: 7,
    name: "carnation",
    title: "빨간색 카네이션",
    description:
      "어버이나 스승의 건강을 비는 마음을 전하기 좋은 빨간색 카네이션입니다.",
    language: "어버이에 대한 사랑",
    color: "red",
  },
  {
    id: 8,
    name: "carnation",
    title: "노란색 카네이션",
    description: "어버이나 스승께 선물하기 좋은 분홍색 카네이션입니다.",
    language: "순수한 사랑",
    color: "yellow",
  },
  {
    id: 9,
    name: "hydrangea",
    title: "흰색 수국",
    description:
      "차분하면서 화사한 모습이어서 부케에 많이 사용하는 수국입니다.",
    language: "넓고 상냥한 마음, 관용",
    color: "white",
  },
  {
    id: 10,
    name: "hydrangea",
    title: "분홍색 수국",
    description:
      "차분하면서 화사한 모습이어서 부케에 많이 사용하는 수국입니다.",
    language: "소녀의 꿈",
    color: "pink",
  },
  {
    id: 11,
    name: "hydrangea",
    title: "보라색 수국",
    description:
      "차분하면서 화사한 모습이어서 부케에 많이 사용하는 수국입니다.",
    language: "진심",
    color: "purple",
  },
  {
    id: 12,
    name: "hydrangea",
    title: "푸른색 수국",
    description:
      "차분하면서 화사한 모습이어서 부케에 많이 사용하는 수국입니다.",
    language: "냉정, 무정",
    color: "blue",
  },
  {
    id: 13,
    name: "peony",
    title: "흰색 작약",
    description: "예쁜 꽃말로 부케에 많이 사용하는 흰색 작약입니다.",
    language: "행복한 결혼",
    color: "white",
  },
  {
    id: 14,
    name: "peony",
    title: "분홍색 작약",
    description: "모란과 비슷하지만 다른, 화사한 모습의 분홍색 작약입니다.",
    language: "수줍음, 부끄러움",
    color: "pink",
  },
  {
    id: 15,
    name: "peony",
    title: "빨간색 작약",
    description: "모란과 비슷하지만 다른, 화사한 모습의 빨간색 작약입니다.",
    language: "성실함",
    color: "red",
  },
  {
    id: 16,
    name: "rose",
    title: "흰색 장미",
    description:
      "사랑을 전할 때 가장 많이 사용되는 베스트셀러, 흰색 장미입니다.",
    language: "순수, 결백, 새로운 시작",
    color: "white",
  },
  {
    id: 17,
    name: "rose",
    title: "붉은색 장미",
    description:
      "사랑을 전할 때 가장 많이 사용되는 베스트셀러, 붉은색 장미입니다.",
    language: "낭만적인 사랑, 아름다움, 용기, 열정",
    color: "red",
  },
  {
    id: 18,
    name: "rose",
    title: "분홍색 장미",
    description:
      "사랑을 전할 때 가장 많이 사용되는 베스트셀러, 분홍색 장미입니다.",
    language: "사랑의 맹세, 행복한 사랑",
    color: "pink",
  },
  {
    id: 19,
    name: "rose",
    title: "노란색 장미",
    description: "귀여운 모습에 친구에게 선물하기 좋은, 노란색 장미입니다.",
    language: "기쁨, 우정, 환영",
    color: "yellow",
  },
  {
    id: 20,
    name: "rose",
    title: "보라색 장미",
    description: "우아한 모습에 사랑을 전하기 좋은 꽃말의 보라색 장미입니다.",
    language: "영원한 사랑",
    color: "purple",
  },
  {
    id: 21,
    name: "gypsophila",
    title: "노란색 안개꽃",
    description: "무언가를 성취한 사람에게 성공하기 좋은, 노란색 안개꽃입니다.",
    language: "성공, 성취",
    color: "yellow",
  },
  {
    id: 22,
    name: "gypsophila",
    title: "분홍색 안개꽃",
    description: "사랑을 전할 때 곁들이기 좋은 분홍색 안개꽃입니다.",
    language: "죽을만큼 사랑합니다.",
    color: "pink",
  },
  {
    id: 23,
    name: "gypsophila",
    title: "빨간색 안개꽃",
    description:
      "행복한 순간을 맞이한 분에게 선물하기 좋은 빨간색 안개꽃입니다.",
    language: "기쁨의 순간",
    color: "red",
  },
  {
    id: 24,
    name: "gypsophila",
    title: "보라색 안개꽃",
    description: "순수하고 깨끗한 마음을 전달하기 좋은 보라색 안개꽃입니다.",
    language: "깨끗한 마음",
    color: "purple",
  },
  {
    id: 25,
    name: "gypsophila",
    title: "푸른색 안개꽃",
    description: "사랑을 전할 때 곁들이기 좋은 푸른색 안개꽃입니다.",
    language: "영원한 사랑",
    color: "blue",
  },
  {
    id: 26,
    name: "gypsophila",
    title: "흰색 안개꽃",
    description: "어디에나 잘 어울려서 자주 사용되는 흰색 안개꽃입니다.",
    language: "죽음, 슬픔, 맑은 마음, 사랑의 성공",
    color: "white",
  },
  {
    id: 27,
    name: "sunflower",
    title: "해바라기",
    description: "특별한 꽃다발을 찾을 때 좋은 선택, 해바라기입니다.",
    language: "동경, 숭배",
    color: "yellow",
  },
  {
    id: 28,
    name: "lisianthus",
    title: "분홍색 리시안사스",
    description: "사랑을 전하기 좋은 밝은 분홍색 리시안사스입니다.",
    language: "사랑스러운 애정",
    color: "pink",
  },
  {
    id: 29,
    name: "lisianthus",
    title: "보라색 리시안사스",
    description:
      "두 사람의 사랑을 널리 알릴 때 사용하기 좋은 보라색 리시안사스입니다.",
    language: "사랑의 공표",
    color: "purple",
  },
  {
    id: 30,
    name: "lisianthus",
    title: "흰색 리시안사스",
    description: "좋은 꽃말 덕분에 부케에 많이 사용하는 흰색 리시안사스입니다.",
    language: "순결, 평생의 유대감",
    color: "white",
  },
  {
    id: 31,
    name: "lisianthus",
    title: "밝은 분홍색 리시안사스",
    description: "사랑을 전하기 좋은 밝은 분홍색 리시안사스입니다.",
    language: "사랑스러운 애정",
    color: "lightpink",
  },
  {
    id: 32,
    name: "lisianthus",
    title: "노란색 리시안사스",
    description: "밝고 명랑한 색의 노란색 리시안사스입니다.",
    language: "기쁨",
    color: "yellow",
  },
  {
    id: 33,
    name: "lisianthus",
    title: "푸른색 리시안사스",
    description: "사랑을 전할 때 사용하기 좋은 푸른색 리시안사스입니다.",
    language: "변치 않는 사랑",
    color: "blue",
  },
  {
    id: 34,
    name: "lilium",
    title: "흰색 백합",
    description: "화려한 모습으로 부케에 많이 사용하는 흰색 백합입니다.",
    language: "순수한 사랑, 순결",
    color: "white",
  },
  {
    id: 35,
    name: "lilium",
    title: "분홍색 백합",
    description: "화려한 모습으로 부케에 많이 사용하는 분홍색 백합입니다.",
    language: "열정, 깨끗함",
    color: "pink",
  },
  {
    id: 36,
    name: "lilium",
    title: "밝은 분홍색 백합",
    description: "화려한 모습으로 부케에 많이 사용하는 밝은 분홍색 백합입니다.",
    language: "핑크빛 사랑",
    color: "lightpink",
  },
  {
    id: 37,
    name: "freesia",
    title: "노란색 프리지아",
    description: "순수한 마음을 전달하기 좋은 노란색 프리지아입니다.",
    language: "순결, 순진한 마음",
    color: "yellow",
  },
  {
    id: 38,
    name: "tulip",
    title: "빨간색 튤립",
    description: "사랑을 전하기 좋은 빨간색 튤립입니다.",
    language: "사랑의 고백, 영원한 사랑",
    color: "red",
  },
  {
    id: 39,
    name: "tulip",
    title: "노란색 튤립",
    description: "화사한 색깔의 노란색 튤립입니다.",
    language: "헛된 사랑, 짝사랑",
    color: "yellow",
  },
  {
    id: 40,
    name: "chrysanthemum",
    title: "흰색 국화",
    description: "애도하는 마음을 전할 때 사용하는 흰색 국화입니다.",
    language: "지혜와 평화, 절개",
    color: "white",
  },
];
