//* 포장지, 리본, 꽃 종류 컨텐츠

//* 포장지
export const wrapper = [
  {
    id: 0,
    name: "종이 포장지",
    description: "어디에나 잘 어울리는 \n 크래프트 소재 종이 포장지",
    color: "brown",
    hex: "#dfd4b9",
  },
  {
    id: 1,
    name: "흰색 포장지",
    description: "차분하고 깔끔한 느낌의 \n 흰색 포장지",
    color: "white",
    hex: "#fffef4",
  },
  {
    id: 2,
    name: "미색 포장지",
    description: "부드러운 느낌을 주는 \n 미색(아이보리색) 포장지",
    color: "ivory",
    hex: "#ece6cc",
  },
  {
    id: 3,
    name: "분홍색 포장지",
    description: "따뜻하고 사랑스러운 느낌의 \n 분홍색 포장지",
    color: "pink",
    hex: "#f9eeee",
  },
  {
    id: 4,
    name: "파란색 포장지",
    description: "누구에게나 선물하기 좋은 \n 파란색 포장지",
    color: "blue",
    hex: "#e1e9f2",
  },
  {
    id: 5,
    name: "회색 포장지",
    description: "꽃을 더 돋보이게 해주는 \n 회색 포장지",
    color: "gray",
    hex: "#c0c0c0",
  },
];

//* 리본
export const ribbon = [
  {
    id: 0,
    name: "끈 리본",
    description: "종이 포장지와 잘 어울리는 \n 끈 리본",
    color: "brown",
  },
  {
    id: 1,
    name: "흰색 리본",
    description: "깔끔하고 밝은 흰색 리본",
    color: "white",
  },
  {
    id: 2,
    name: "미색 리본",
    description: "부드러운 느낌의 미색 리본",
    color: "ivory",
  },
  {
    id: 3,
    name: "분홍색 리본",
    description: "귀여운 느낌의 분홍색 리본",
    color: "pink",
  },
  {
    id: 4,
    name: "파란색 리본",
    description: "밝은 느낌의 옅은 파란색 리본",
    color: "blue",
  },
  {
    id: 5,
    name: "회색 리본",
    description: "꽃을 더 돋보이게 해주는 \n 회색 리본",
    color: "gray",
  },
];

//* 꽃
export const flower = [
  {
    id: 1,
    name: "calla",
    title: "흰색 카라",
    description: "카라입니다.",
    language: "꽃말",
    color: "white",
  },
  {
    id: 2,
    name: "calla",
    title: "옅은 분홍색 카라",
    description: "카라입니다.",
    language: "꽃말",
    color: "lightpink",
  },
  {
    id: 3,
    name: "calla",
    title: "분홍색 카라",
    description: "카라입니다.",
    language: "꽃말",
    color: "pink",
  },
  {
    id: 4,
    name: "calla",
    title: "노란색 카라",
    description: "카라입니다.",
    language: "꽃말",
    color: "yellow",
  },
  {
    id: 5,
    name: "carnation",
    title: "흰색 카네이션",
    description: "카네이션입니다.",
    language: "꽃말",
    color: "white",
  },
  {
    id: 6,
    name: "carnation",
    title: "분홍색 카네이션",
    description: "카네이션입니다.",
    language: "꽃말",
    color: "pink",
  },
  {
    id: 7,
    name: "carnation",
    title: "빨간색 카네이션",
    description: "카네이션입니다.",
    language: "꽃말",
    color: "red",
  },
  {
    id: 8,
    name: "carnation",
    title: "노란색 카네이션",
    description: "카네이션입니다.",
    language: "꽃말",
    color: "yellow",
  },
  {
    id: 9,
    name: "hydrangea",
    title: "흰색 수국",
    description: "수국입니다.",
    language: "꽃말",
    color: "white",
  },
  {
    id: 10,
    name: "hydrangea",
    title: "분홍색 수국",
    description: "수국입니다.",
    language: "꽃말",
    color: "pink",
  },
  {
    id: 11,
    name: "hydrangea",
    title: "보라색 수국",
    description: "수국입니다.",
    language: "꽃말",
    color: "purple",
  },
  {
    id: 12,
    name: "hydrangea",
    title: "푸른색 수국",
    description: "수국입니다.",
    language: "꽃말",
    color: "blue",
  },
  {
    id: 13,
    name: "peony",
    title: "흰색 작약",
    description: "작약입니다.",
    language: "꽃말",
    color: "white",
  },
  {
    id: 14,
    name: "peony",
    title: "분홍색 작약",
    description: "작약입니다.",
    language: "꽃말",
    color: "pink",
  },
  {
    id: 15,
    name: "peony",
    title: "빨간색 작약",
    description: "작약입니다.",
    language: "꽃말",
    color: "red",
  },
  {
    id: 16,
    name: "rose",
    title: "흰색 장미",
    description: "장미입니다.",
    language: "꽃말",
    color: "white",
  },
  {
    id: 17,
    name: "rose",
    title: "붉은색 장미",
    description: "장미입니다.",
    language: "꽃말",
    color: "red",
  },
  {
    id: 18,
    name: "rose",
    title: "분홍색 장미",
    description: "장미입니다.",
    language: "꽃말",
    color: "pink",
  },
  {
    id: 19,
    name: "rose",
    title: "노란색 장미",
    description: "장미입니다.",
    language: "꽃말",
    color: "yellow",
  },
  {
    id: 20,
    name: "rose",
    title: "보라색 장미",
    description: "장미입니다.",
    language: "꽃말",
    color: "purple",
  },
  {
    id: 21,
    name: "gypsophila",
    title: "노란색 안개꽃",
    description: "안개꽃입니다.",
    language: "꽃말",
    color: "yellow",
  },
  {
    id: 22,
    name: "gypsophila",
    title: "분홍색 안개꽃",
    description: "안개꽃입니다.",
    language: "꽃말",
    color: "pink",
  },
  {
    id: 23,
    name: "gypsophila",
    title: "빨간색 안개꽃",
    description: "안개꽃입니다.",
    language: "꽃말",
    color: "red",
  },
  {
    id: 24,
    name: "gypsophila",
    title: "보라색 안개꽃",
    description: "안개꽃입니다.",
    language: "꽃말",
    color: "purple",
  },
  {
    id: 25,
    name: "gypsophila",
    title: "푸른색 안개꽃",
    description: "안개꽃입니다.",
    language: "꽃말",
    color: "blue",
  },
  {
    id: 26,
    name: "gypsophila",
    title: "흰색 안개꽃",
    description: "안개꽃입니다.",
    language: "꽃말",
    color: "white",
  },
  {
    id: 27,
    name: "sunflower",
    title: "해바라기",
    description: "해바라기꽃입니다.",
    language: "꽃말",
    color: "yellow",
  },
  {
    id: 28,
    name: "lisianthus",
    title: "분홍색 리시안사스",
    description: "리시안사스입니다.",
    language: "꽃말",
    color: "pink",
  },
  {
    id: 29,
    name: "lisianthus",
    title: "보라색 리시안사스",
    description: "리시안사스입니다.",
    language: "꽃말",
    color: "purple",
  },
  {
    id: 30,
    name: "lisianthus",
    title: "흰색 리시안사스",
    description: "리시안사스입니다.",
    language: "꽃말",
    color: "white",
  },
  {
    id: 31,
    name: "lisianthus",
    title: "밝은 분홍색 리시안사스",
    description: "리시안사스입니다.",
    language: "꽃말",
    color: "lightpink",
  },
  {
    id: 32,
    name: "lisianthus",
    title: "노란색 리시안사스",
    description: "리시안사스입니다.",
    language: "꽃말",
    color: "yellow",
  },
  {
    id: 33,
    name: "lisianthus",
    title: "푸른색 리시안사스",
    description: "리시안사스입니다.",
    language: "꽃말",
    color: "blue",
  },
  {
    id: 34,
    name: "lilium",
    title: "흰색 백합",
    description: "백합입니다.",
    language: "꽃말",
    color: "white",
  },
  {
    id: 35,
    name: "lilium",
    title: "분홍색 백합",
    description: "백합입니다.",
    language: "꽃말",
    color: "pink",
  },
  {
    id: 36,
    name: "lilium",
    title: "밝은 분홍색 백합",
    description: "백합입니다.",
    language: "꽃말",
    color: "lightpink",
  },
  {
    id: 37,
    name: "freesia",
    title: "노란색 프리지아",
    description: "프리지아입니다.",
    language: "꽃말",
    color: "yellow",
  },
  {
    id: 38,
    name: "tulip",
    title: "빨간색 튤립",
    description: "튤립입니다.",
    language: "꽃말",
    color: "red",
  },
  {
    id: 39,
    name: "tulip",
    title: "노란색 튤립",
    description: "튤립입니다.",
    language: "꽃말",
    color: "yellow",
  },
  {
    id: 40,
    name: "chrysanthemum",
    title: "흰색 국화",
    description: "국화입니다.",
    language: "꽃말",
    color: "white",
  },
];
