export const RecipeContents = [
  {
    title: "부케",
    description: "부케에 사용하기 좋은 꽃 조합의 꽃다발이에요.",
    flower_kind: [0, 1, 2, 8, 12, 29],
    package: 0,
    size: 4,
    wrapper: 1,
    ribbon: 1,
    flowers: [0, 1, 2, 8, 12, 29, 0, 0, 0],
  },
  {
    title: "돌잔치",
    description: "돌잔치에 사용하기 좋은 꽃 조합의 꽃풍선이에요.",
    flower_kind: [8, 18, 32, 37],
    package: 2,
    size: 2,
    wrapper: 1,
    ribbon: null,
    flowers: [8, 18, 32, 37, 8],
  },
  {
    title: "장례식",
    description: "회색 포장지의 흰색 국화 꽃다발이에요.",
    flower_kind: [39],
    package: 0,
    size: 4,
    wrapper: 5,
    ribbon: 5,
    flowers: [39, 39, 39, 39, 39, 39, 39, 39, 39],
  },
  {
    title: "고백",
    description: "하얀 안개꽃과 빨간 장미의 조화는 '죽을 만큼 사랑합니다'라는 뜻이래요.",
    flower_kind: [17, 21, 25],
    package: 0,
    size: 4,
    wrapper: 1,
    ribbon: 1,
    flowers: [17, 21, 25, 17, 21, 25, 17, 21, 25],
  },
  {
    title: "친구에게 주는 선물",
    description: "친구에게 선물하기 좋은 꽃말만 모아 봤어요!",
    flower_kind: [18, 20, 27],
    package: 0,
    size: 4,
    wrapper: 1,
    ribbon: 1,
    flowers: [18, 20, 27, 18, 20, 27, 18, 20, 27],
  },
  {
    title: "졸업식",
    description: "성공과 새로운 시작을 응원하는 마음을 담은 꽃다발이에요.",
    flower_kind: [14, 15, 18, 37],
    package: 0,
    size: 4,
    wrapper: 1,
    ribbon: 1,
    flowers: [14, 15, 18, 37, 14, 15, 18, 37, 14],
  },
  {
    title: "성공에 대한 축하",
    description: "무언가를 이룬 분에게 선물하기 좋은 꽃말 조합의 꽃다발이에요.",
    flower_kind: [17, 18, 29, 23, 32],
    package: 0,
    size: 4,
    wrapper: 1,
    ribbon: 1,
    flowers: [17, 18, 29, 23, 32, 17, 18, 29, 23],
  },
  {
    title: "위로",
    description: "오래 보고 위로받을 수 있게끔 좋은 꽃말의 꽃을 모아 꽃병을 준비해 봤어요.",
    flower_kind: [8, 10, 19, 23],
    package: 1,
    size: 2,
    wrapper: null,
    ribbon: null,
    flowers: [8, 10, 19, 23, 8],
  },
  {
    title: "어버이의 날",
    description: "이번 어버이의 날에는 오랫동안 사랑을 느낄 수 있게 꽃병으로 선물드리는건 어떨까요?",
    flower_kind: [6],
    package: 1,
    size: 2,
    wrapper: null,
    ribbon: null,
    flowers: [6, 6, 6, 6, 6],
  },
  {
    title: "스승의 날",
    description: "감사한 마음을 전하기 좋은 꽃 조합의 꽃다발이에요.",
    flower_kind: [5, 6, 26],
    package: 0,
    size: 4,
    wrapper: 1,
    ribbon: 1,
    flowers: [5, 6, 26, 5, 6, 26, 5, 6, 26],
  },
  {
    title: "성년의 날",
    description: "깨끗한 마음으로, 새로운 시작을 응원하기 좋은 조합의 꽃들이에요.",
    flower_kind: [9, 15, 17],
    package: 0,
    size: 4,
    wrapper: 1,
    ribbon: 1,
    flowers: [9, 15, 17, 9, 15, 17, 9, 15, 17],
  },
  {
    title: "아무것도 주기 싫은데 주긴 줘야 할 때",
    description: "그럴 때 있잖아요, 냉정과 무정이란 뜻의 푸른 수국은 어때요?",
    flower_kind: [11],
    package: 0,
    size: 1,
    wrapper: 4,
    ribbon: 4,
    flowers: [11, 11, 11],
  },
];
