spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: flowerlikeu209@gmail.com
    password: flgzbojavpqcleji
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
security-aes256:
  key: 45672301234563890789890121410567