server:
  port: 8080
  address: localhost
  servlet:
    context-path: /api
spring:
  data:
    mongodb:
      host: k7b209.q.ssafy.io
      port: 27017
      authentication-database: admin
      username: ssafy
      password: ks7sba2f0y9
      database: fly